version: '3.8'

services:
  web:
    build: ./website
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./website/:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - ./.env.dev
  
volumes:
  postgres_data: